dist: trusty
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
install:
  - npm install
script: npm run lint && npm test
deploy:
  provider: npm
  email: development@hive.pt
  api_key:
    secure: ehnw0wMkVbvsaiGX7Xz+tktXe+Ver2BDtvmtP9g9mLQwSGE+rsNW0c2H+T+xHQZEpTEfUHVtnOFzP/O2qJEF/pqyaTl1NkQA9Jmh5qHfOo+CNLyNDlnqb4tf5g5rU3VTElqv/OGvEZNHVoYBWKD4QRYitHgt9rk5dtINpS9x47xIw0LKQso34VNvYHw6xH274KbXywqlbWK7LCRmwGEAMBnIfPzXzJ7QJxcYrRcGaDulWWqbptfebk6jwzxU3/JHWfdb9sa4SjYbe4MafBJTzQGYQIaKGUcz8W62noOpaFi0b2+Hmso8qP1zuVu/QzFY+yzvVkDicsTWYpWEmBQbZYIyh1bpXdLxmML/lgZHkcTRKr0CGCCvjD8iL4g0GnNKIwRcZe+cGpoB6y+0q5OnOq+utJ0o5sVuavPev1qv7NB0xS1jAB0w/8FYfnQYzVbbtDfHc1QGsfw4Ddso3A/qZu5bKiHHyceoZ5Zvg2BgEoN9nhgXo7a4bDHp60Ivjf0Y1Ts+g0LrfbPrkxtmpXjCqaco5KSjcWC9qjHD/6uUm3IxhpnAuFC0GNJ6j36Cp8V8w8vOotj4FtsJQq55QXkckFSg/PE5U2i07T2uScQQ2vVmquYcfU4vwDFFVp0Hu+gOyApJjCQDoCDhAfr1mYdYqjrbJTaD6AWce0kAqAp75I8=
  on:
    tags: true
    node_js: "8"
