name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20, 22, 24, 26]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}-trixie-slim
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v7
      - name: Print Node.js information
        run: node --version
      - name: Install package
        run: npm install
      - name: Install package (development)
        run: npm install --only=dev
      - name: Verify Javascript code linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
  build-python:
    name: Build Python
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v7
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
        env:
          PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"
      - name: Print Python information
        run: python --version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Verify Python code formatting
        if: matrix.python-version == '3.14'
        run: |
          pip install black
          black . --check
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
